services:
  project:
    profiles: [ "manual" ]
    build:
      context: ../projects/${ACTIVE_PROJECT}
      dockerfile: ../../docker/Dockerfile.project
      args:
        PROJECT_NAME: ${ACTIVE_PROJECT:-}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    volumes:
      - ../projects/${ACTIVE_PROJECT}:/project
      - ../common:/project/src/common
    command: python3 src/train.py
    depends_on:
      mlflow:
        condition: service_healthy
      minio:
        condition: service_healthy

  mlflow:
    build:
      context: ..
      dockerfile: docker/Dockerfile.mlflow
    ports:
      - "5000:5000"
    environment:
      MLFLOW_ARTIFACT_URI: s3://mlflow/
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    volumes:
      - ../volumes/mlflow:/mlflow
    command: mlflow server --backend-store-uri=sqlite:////mlflow/mlflow.db --default-artifact-root=s3://mlflow/ --host=0.0.0.0
    healthcheck:
      test: curl -f http://localhost:5000 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ../volumes/minio/data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address=:9001
    healthcheck:
      test: curl -f http://localhost:9000/minio/health/ready || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  # One-time setup container to ensure the 'mlflow' bucket exists in MinIO
  minio-setup:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
        mc alias set local http://minio:9000 minioadmin minioadmin &&
        mc mb local/mlflow || true
      "

volumes:
  minio_data: {}
