FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
   python3-pip \
   && rm -rf /var/lib/apt/lists/*

# Copy source and install Python dependencies
COPY app/requirements.txt .
RUN pip3 install --upgrade pip && pip3 install -r requirements.txt

COPY app /app

CMD ["python3", "src/train.py"]