FROM ghcr.io/mlflow/mlflow

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*
RUN pip install boto3

WORKDIR /mlflow

CMD mlflow server \
    --backend-store-uri=sqlite:///mlflow.db \
    --default-artifact-root=s3://mlflow/ \
    --host=0.0.0.0