ARG PROJECT_NAME
FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

WORKDIR /project

RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./requirements.txt
RUN pip3 install --upgrade pip && pip3 install debugpy -r requirements.txt
ENV PYTHONPATH="${PYTHONPATH}:/projects/common"

CMD ["python3", "src/train.py"]
