defaults:
  - sweep
  - override hydra/sweeper: optuna
  - _self_

git:
  commit: ${oc.env:GIT_COMMIT}

project:
  name: handwritten-classifier
  run_prefix: base

data:
  path: ./ephemeral/data/
  num_classes: 26

models:
  baseline:
    name: handwritten-cnn-baseline
    class_path: models.baseline_model.BaselineModel

train:
  lr: 0.001
  batch_size: 64
  num_workers: 8
  epochs: 5
  model: baseline

hydra:
  run:
    dir: ./ephemeral/singlerun/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./ephemeral/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}